#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEFAULT_JAVA11_HOME="$HOME/.local/jdks/temurin-11"
DEFAULT_ANDROID_SDK_ROOT="$HOME/.local/android-sdk"
DEFAULT_TASK="assembleCloudlessDebug"

usage() {
  cat <<'EOF'
Build the Simpletask Revived cloudless/local Android flavor.

Usage:
  scripts/build_cloudless.sh [gradle-task] [-- extra gradle args]

Examples:
  scripts/build_cloudless.sh
  scripts/build_cloudless.sh installCloudlessDebug
  scripts/build_cloudless.sh assembleCloudlessRelease -- --stacktrace

Environment overrides:
  JAVA11_HOME         Path to the JDK 11 installation to use for Gradle
  ANDROID_SDK_ROOT    Path to the Android SDK
  ANDROID_HOME        Optional alias for ANDROID_SDK_ROOT

Notes:
  - This script forces Gradle to run with Java 11 because this project's
    current Android/Kotlin toolchain builds successfully with JDK 11.
  - If local.properties is missing, the script creates one pointing at the SDK.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

TASK="$DEFAULT_TASK"
if [[ "${1:-}" != "" && "${1:-}" != "--" ]]; then
  TASK="$1"
  shift
fi

EXTRA_ARGS=()
if [[ "${1:-}" == "--" ]]; then
  shift
  EXTRA_ARGS=("$@")
fi

JAVA11_HOME="${JAVA11_HOME:-$DEFAULT_JAVA11_HOME}"
ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-$DEFAULT_ANDROID_SDK_ROOT}}"
LOCAL_PROPERTIES="$REPO_ROOT/local.properties"
GRADLEW="$REPO_ROOT/gradlew"

if [[ ! -x "$GRADLEW" ]]; then
  echo "error: gradlew not found at $GRADLEW" >&2
  exit 1
fi

if [[ ! -x "$JAVA11_HOME/bin/java" ]]; then
  cat >&2 <<EOF
error: JDK 11 not found at $JAVA11_HOME
Set JAVA11_HOME to a valid JDK 11 install before running this script.
EOF
  exit 1
fi

if [[ ! -d "$ANDROID_SDK_ROOT" ]]; then
  cat >&2 <<EOF
error: Android SDK not found at $ANDROID_SDK_ROOT
Set ANDROID_SDK_ROOT (or ANDROID_HOME) to a valid SDK path before running this script.
EOF
  exit 1
fi

if [[ ! -f "$LOCAL_PROPERTIES" ]]; then
  cat > "$LOCAL_PROPERTIES" <<EOF
## This file is automatically generated by scripts/build_cloudless.sh for local Android builds.
# Do not commit this file.
sdk.dir=$ANDROID_SDK_ROOT
EOF
  echo "Created $LOCAL_PROPERTIES"
fi

export JAVA_HOME="$JAVA11_HOME"
export PATH="$JAVA_HOME/bin:$PATH"
export ANDROID_SDK_ROOT
export ANDROID_HOME="$ANDROID_SDK_ROOT"

echo "Repo root:        $REPO_ROOT"
echo "Gradle task:      $TASK"
echo "JAVA_HOME:        $JAVA_HOME"
echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"

cd "$REPO_ROOT"
exec "$GRADLEW" "$TASK" "${EXTRA_ARGS[@]}"
